name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g @angular/cli
          ng version

      - name: Build Angular app
        run: |
          echo "Building with production configuration..."
          npm run build
          echo "Build completed. Checking output..."
          ls -la dist/fitcoach-fe/
          echo "Checking for index.html..."
          if [ -f "dist/fitcoach-fe/index.html" ]; then
            echo "✅ index.html found"
          else
            echo "❌ index.html not found"
            echo "Files in dist/fitcoach-fe/:"
            find dist/fitcoach-fe/ -name "*.html"
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_PLANT_0835BED03 }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist/fitcoach-fe"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
